### ISSUE TITLE
NPM package missing files

### ISSUE THREAD

**Issue by robertkern** [okdistribute/spake2-wasm#2]
Thanks for putting this together! I'm keen to use the package but after installing from `npm` it seems to be missing files.

Under `node_modules/spake2-wasm` it only has:

- `LICENSE`
- `package.json`
- `README.md`

Just wondering if this is something you're aware of?
Tried building it myself but running into issues on macOS - I might need to try Linux later.

Thanks!

**Comment by okdistribute** [comment]
Hey @robertkern 
I just tried to re-build this package locally and it failed for me, I tried for 20 minutes and couldn't get it to work despite updating to latest versions of rust & clang.

Are you able to build it on your machine?

**Comment by okdistribute** [comment]
I just realized by looking at the example, that `1.0.0` was released but it shouldn't have been.

Try `^0.2.0`, that worked for me
